### ISSUE TITLE
0.2.4 source tarball is missing all js assets

### ISSUE THREAD

**Issue by antonio-rojas** [jupyter-server/jupyter_server_mathjax#14]
## Description

The 0.2.4 source tarball on PyPi is only 7.2KB, it's missing the entire js dir.

**Comment by vidartf** [comment]
Good spot. This is reproducible locally as well when trying to create a new sdist. I will investigate.

**Comment by vidartf** [comment]
I've added a PR to fix this in #15, but I cannot modify the sdist already on PyPI. Underlying cause of the faulty problem was that I sued the old `python setup.py sdist` command to build the release, and either something had changed in an underlying package, or the project was misconfigured (or a combination of the two).

**Comment by vidartf** [comment]
Closed with release of 0.2.5 via #16.
